name: bookings
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dash: ^1.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.0.0
  lottie: ^2.3.2
  liquid_pull_to_refresh: ^3.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
